name: Publish NPM package

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/test.yaml

  publish:
    name: Publish ngx-fudis to NPM
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - name: Install Angular CLI
        run: npm i -g @angular/cli@v13-lts
      - name: Install dependencies
        run: npm ci
        working-directory: ngx-fudis
      - name: Build ngx-fudis
        run: ng build ngx-fudis
        working-directory: ngx-fudis
      - name: Build library schematics
        run: npm ci && npm run build
        working-directory: ngx-fudis/projects/ngx-fudis
      - name: Publish @funidata/ngx-fudis
        id: npm-publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ngx-fudis/dist/ngx-fudis/package.json
          check-version: true
          access: public
          tag: latest
      - name: Create GitHub release
        if: ${{ steps.npm-publish.outputs.type != 'none' }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: format('v{0}', steps.npm-publish.outputs.version)
          body: Changelog and link to Storybook to be included here once we reach v1 or earlier...
